services:
  certificate-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certificate-management-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      # Пути к файлам
      - DB_PATH=/app/data/certificates.db
      - OUTPUT_DIR=/app/output
      - LOG_DIR=/app/logs
      # API настройки
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_WORKERS=1
      - API_RELOAD=false
      # Параметры генерации данных по умолчанию
      - NUM_CLIENTS=${NUM_CLIENTS:-1000}
      - NUM_CERTIFICATES=${NUM_CERTIFICATES:-2000}
      # Опциональные параметры для ручного управления
      - BATCH_SIZE=${BATCH_SIZE:-}
      - NUM_WORKERS=${NUM_WORKERS:-}
      - BUFFER_SIZE=${BUFFER_SIZE:-}
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  net:
    driver: bridge
    name: certificate-net